/* Generated By:JavaCC: Do not edit this line. RVCParserConstants.java */
package RVC.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RVCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int LBRACE = 2;
  /** RegularExpression Id. */
  int RBRACE = 3;
  /** RegularExpression Id. */
  int LPAREN = 4;
  /** RegularExpression Id. */
  int RPAREN = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int AT = 7;
  /** RegularExpression Id. */
  int INCLUDE = 8;
  /** RegularExpression Id. */
  int LT = 9;
  /** RegularExpression Id. */
  int GT = 10;
  /** RegularExpression Id. */
  int EVENT = 11;
  /** RegularExpression Id. */
  int ID = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int LETTER = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"@\"",
    "\"#include\"",
    "\"<\"",
    "\">\"",
    "\"event\"",
    "<ID>",
    "<DIGIT>",
    "<LETTER>",
    "\":\"",
  };

}
