/* Generated By:JavaCC: Do not edit this line. RVCParserConstants.java */
package RVCParser.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RVCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int LBRACE = 2;
  /** RegularExpression Id. */
  int RBRACE = 3;
  /** RegularExpression Id. */
  int AT = 4;
  /** RegularExpression Id. */
  int EVENT = 5;
  /** RegularExpression Id. */
  int ID = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int LETTER = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"{\"",
    "\"}\"",
    "\"@\"",
    "\"event\"",
    "<ID>",
    "<DIGIT>",
    "<LETTER>",
    "\":\"",
  };

}
