package com.runtimeverification.rvmonitor.examples.llvmmop;

import com.runtimeverification.rvmonitor.c.rvc.Main;
import com.runtimeverification.rvmonitor.util.Tool;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;

/**
 * Base class for llvmmop examples JUnit tests.
 * @author TraianSF
 */
public class TestHelper {
    public static final String RVC = "__RVC_";
    public static final String MONITOR_BC = "_Monitor.bc";
    protected String specPath;
    protected String specName;
    File specFile;
    private FileSystem fileSystem;
    private Path specPathParent;

    @Before
    public void setUp() throws Exception {
        fileSystem = FileSystems.getDefault();
        specPathParent = fileSystem.getPath(specPath).getParent();
        specFile = specPathParent.toFile();

    }

    /**
     * Calls rv-monitor on the specification described by {@code specPath} and relocates files appropriately.
     * If the monitor was already generated, the method does not generate it again.
     * @throws Exception
     */
    @Test
    public void testMonitor() throws Exception {
        if (Files.exists(fileSystem.getPath(specPathParent.toString(), RVC + specName + MONITOR_BC))) {
            return;
        }
        deleteFiles(false,
                RVC + specName + MONITOR_BC,
                "Makefile",
                "Makefile.instrument",
                "aspect.map"
        );
        Main.main(new String[]{"-llvm", specPath});
        relocateFiles(
                RVC + specName + MONITOR_BC,
                "Makefile.instrument",
                "Makefile.new",
                "aspect.map"
        );

        Files.move(
                fileSystem.getPath(specPathParent.toString(), "Makefile.new"),
                fileSystem.getPath(specPathParent.toString(), "Makefile")
        );
    }


    /**
     * Tests the usual build-test-instument-test-uninstrument-test cycle.
     * Matches precomputed expected output files against the output generated by the tests.
     * @throws Exception
     */
    @Test
    public void testTest() throws Exception {
        testMonitor();
        testCommand(null, "make", "clean");
        testCommand(null, "make");
        testCommand("tests/original", "make", "-f", "Makefile.original", "test");
        testCommand(null, "make", "instrument");
        testCommand("tests/instrumented", "make", "-f", "Makefile.original", "test");
        testCommand(null, "make", "uninstrument");
        testCommand("tests/original", "make", "-f", "Makefile.original", "test");

    }

    private void testCommand(String expectedFilePrefix, String... command) throws Exception {
        testMonitor();
        ProcessBuilder processBuilder = new ProcessBuilder(command);
        processBuilder.directory(specFile);
        String actualOutFile = null;
        String testsPrefix;
        String actualErrFile = null;
        String expectedOutFile = null;
        String expectedErrFile = null;
        if (expectedFilePrefix != null) {
            testsPrefix = specPathParent.toString() + "/" + expectedFilePrefix;
            actualOutFile = testsPrefix + ".actual.out";
            actualErrFile = testsPrefix + ".actual.err";
            expectedOutFile = testsPrefix + ".expected.out";
            expectedErrFile = testsPrefix + ".expected.err";
            processBuilder.redirectError(new File(actualErrFile));
            processBuilder.redirectOutput(new File(actualOutFile));
        }
        Process process = processBuilder.start();
        int returnCode = process.waitFor();
        Assert.assertEquals("Expected no error during" + Arrays.toString(command) + ".", 0, returnCode);
        if (expectedFilePrefix != null) {
            Assert.assertEquals(".out files should be the same", Tool.convertFileToString(expectedOutFile),
                    Tool.convertFileToString(actualOutFile));
            Assert.assertEquals(".out files should be the same", Tool.convertFileToString(expectedErrFile),
                    Tool.convertFileToString(actualErrFile));
        }
    }

    private void relocateFiles(String... files) throws IOException {
        for (String s : files) {
            Path path = fileSystem.getPath(specPathParent.toString(), s);
            Files.move(
                    fileSystem.getPath(s),
                    path
            );
        }
    }

    private void deleteFiles(boolean fail, String... files) throws IOException {
        for (String s : files) {
            Path toDelete = fileSystem.getPath(specPathParent.toString(), s);
            if (fail) {
                Files.delete(toDelete);
            } else {
                Files.deleteIfExists(toDelete);
            }
        }
    }
}
