.SUFFIXES: .bc

.c.bc:
	clang $(CFLAGS) $< -o $@ -c -emit-llvm

.bc.o:
	llc -filetype=obj $< -o $@

.o:
	clang $(LDFLAGS) $@.o -o $@

all: test1 test2

test1.o: test_1/test1.bc
	llc -filetype=obj $< -o $@

test2.o: test_2/test2.bc
	llc -filetype=obj $< -o $@
	
test: all
	-@./test1
	-@./test2
	
clean:
	rm -f test_1/*.bc test_2/*.bc test1 test1.o test2 test2.o
