
/**************************
 * 00: Forward-Driving Car.c
 * Generated by KeYmaera X
 **************************/


(/**************************
 *
 * Generated by KeYmaera X
 **************************/

#include <math.h>
#include <stdbool.h>

typedef struct parameters {
  long double A;
  long double B;
} parameters;

typedef struct state {
  long double a;
  long double v;
  long double x;
} state;

typedef struct input input;

state ctrlStep(state curr, const parameters* const params, const input* const in) {
  struct { state state; int success; } prg = { .state=curr, .success=0 };
  while (!prg.success) {
    {
      {
        state reset = prg.state;
        {
          prg.success = (prg.state.v <= 5.0L);
        }
        if (prg.success) {
          prg.state.a = params->A; prg.success = 1;
        }
        if (!prg.success) prg.state = reset;
      }
      if (!prg.success) {
        state reset = prg.state;
        {
          state reset = prg.state;
          prg.state.a = 0.0L; prg.success = 1;
          if (!prg.success) prg.state = reset;
        }
        if (!prg.success) {
          state reset = prg.state;
          prg.state.a = -(params->B); prg.success = 1;
          if (!prg.success) prg.state = reset;
        }
        if (!prg.success) prg.state = reset;
      }
    }
    if (prg.success) {
      prg.success = 1; /* done choosing actuator set values */
    }
  }
  return prg.state;
},)

int main() {
  /* control loop stub */
  parameters params = { .A=1.0 };
  while (true) {
    state current; /* read sensor values, e.g., = { .x=0.0 }; */
    state input;   /* resolve non-deterministic assignments, e.g., = { .x=0.5 }; */
    state post = ctrlStep(current, params, input);
    /* hand post actuator set values to actuators */
  }
  return 0;
}
