
/**************************
 * 00: Forward-Driving Car.c
 **************************/


/**************************
 * Generated by KeYmaera X,
 * then hand-edited to extract struct declaration
 * into header "forward_driving_car.h", and add
 * the "step" function implementing the system evolution.
 * (Untouched KeYmarea X output is in "00_ Forward-Driving Car.c")
 **************************/

#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include "forward_driving_car.h"
#include "monitor.h"

state ctrlStep(state curr, const parameters* const params) {
  struct { state state; int success; } prg = { .state=curr, .success=0 };
  while (!prg.success) {
    {
      {
        state reset = prg.state;
        {
          prg.success = (prg.state.v <= 5.0L);
        }
        if (prg.success) {
          prg.state.a = params->A; prg.success = 1;
        }
        if (!prg.success) prg.state = reset;
      }
      if (!prg.success) {
        state reset = prg.state;
        {
          state reset = prg.state;
          prg.state.a = 0.0L; prg.success = 1;
          if (!prg.success) prg.state = reset;
        }
        if (!prg.success) {
          state reset = prg.state;
          prg.state.a = -(params->B); prg.success = 1;
          if (!prg.success) prg.state = reset;
        }
        if (!prg.success) prg.state = reset;
      }
    }
    if (prg.success) {
      prg.success = 1; /* done choosing actuator set values */
    }
  }
  return prg.state;
}


state step(state prev, double timestep) {
  state next;
  next.x = prev.x + timestep*prev.v + timestep*(prev.a*prev.a)/2;
  next.v = prev.v + timestep*prev.a;
  next.a = prev.a;
  return next;
}

int main() {
  /* control loop stub */
  int iteration = 0;
  parameters params = { .A=0.1, .B=1.0 };
  state current = {.x=0.0, .v=0.1, .a=0.0};
  while (++iteration <= 1000) {
    printf("Iteration %5d, %s x=%9.6Lf, v=%9.6Lf, a=%9.6Lf\n",
      iteration, failsafe_mode ? "FAILSAFE" : "        ", current.x, current.v, current.a);
    state post = ctrlStep(current, &params);
    if (failsafe_mode) {
      post.a = 0.05;
    }
    current = step(post, 0.1);
  }
  return 0;
}
